import turtle
turtle.pensize(10)
turtle.speed(50)
#绿色
turtle.color("white","#7fba00")
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()

#黄色
turtle.color("white","#ffb901")
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()

#蓝色
turtle.color("white","#01a4ef")
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()

#红色
turtle.color("white","#f25022")
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()

turtle.penup()
turtle.goto(-150,-310)
turtle.color("#737373")
turtle.write("Microsoft",font=("rockwell",50,"normal"))
turtle.hideturtle
